sensor:
  - platform: modbus_controller
    modbus_controller_id: brink
    name: "Brink Druck Zuluft"
    address: 4023
    register_type: read
    value_type: S_WORD
    unit_of_measurement: "Pa"
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: brink
    name: "Brink Druck Abluft"
    address: 4024
    register_type: read
    value_type: S_WORD
    unit_of_measurement: "Pa"
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: brink
    id: brink_supply_fan_status_code
    name: "Brink Status Zuluftventilator Code"
    address: 4030
    register_type: read
    value_type: U_WORD
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: brink
    id: brink_exhaust_fan_status_code
    name: "Brink Status Abluftventilator Code"
    address: 4040
    register_type: read
    value_type: U_WORD
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: brink
    name: "Brink Sollwert Zuluft"
    address: 4031
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "m³/h"
    state_class: measurement
  - platform: modbus_controller
    modbus_controller_id: brink
    name: "Brink Aktuelle Zuluft"
    address: 4032
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "m³/h"
    state_class: measurement
  - platform: modbus_controller
    modbus_controller_id: brink
    name: "Brink Massenstrom Zuluft"
    address: 4033
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "kg/h"
    state_class: measurement
  - platform: modbus_controller
    modbus_controller_id: brink
    name: "Brink Drehzahl Zuluftventilator"
    address: 4034
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "rpm"
    state_class: measurement
  - platform: modbus_controller
    modbus_controller_id: brink
    name: "Brink Drehzahl Zuluft Anemometer"
    address: 4035
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "rpm"
    state_class: measurement
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: brink
    name: "Brink Sollwert Abluft"
    address: 4041
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "m³/h"
    state_class: measurement
  - platform: modbus_controller
    modbus_controller_id: brink
    name: "Brink Aktuelle Abluft"
    address: 4042
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "m³/h"
    state_class: measurement
  - platform: modbus_controller
    modbus_controller_id: brink
    name: "Brink Massenstrom Abluft"
    address: 4043
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "kg/h"
    state_class: measurement
  - platform: modbus_controller
    modbus_controller_id: brink
    name: "Brink Drehzahl Abluftventilator"
    address: 4044
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "rpm"
    state_class: measurement
  - platform: modbus_controller
    modbus_controller_id: brink
    name: "Brink Drehzahl Abluft Anemometer"
    address: 4045
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "rpm"
    state_class: measurement
    entity_category: diagnostic
