sensor:
  - platform: modbus_controller
    modbus_controller_id: brink
    name: "Brink Zulufttemperatur ins Haus"
    address: 4036
    register_type: read
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
      - filter_out: 999.9
  - platform: modbus_controller
    modbus_controller_id: brink
    name: "Brink Fortlufttemperatur nach draußen"
    address: 4046
    register_type: read
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
      - filter_out: 999.9
  - platform: modbus_controller
    modbus_controller_id: brink
    name: "Brink Feuchtigkeit Zuluft"
    address: 4037
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "%"
    device_class: humidity
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
      - filter_out: 999.9
  - platform: modbus_controller
    modbus_controller_id: brink
    name: "Brink Feuchtigkeit Fortluft"
    address: 4047
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "%"
    device_class: humidity
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
      - filter_out: 999.9
  - platform: modbus_controller
    modbus_controller_id: brink
    name: "Brink Außenlufttemperatur NTC1"
    address: 4081
    register_type: read
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
      - filter_out: 999.9
  - platform: modbus_controller
    modbus_controller_id: brink
    name: "Brink NTC2 Temperatur"
    address: 4082
    register_type: read
    value_type: S_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
      - filter_out: 999.9
  - platform: modbus_controller
    modbus_controller_id: brink
    name: "Brink RHT Luftfeuchtigkeit"
    address: 4083
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "%"
    device_class: humidity
    state_class: measurement
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
      - filter_out: 999.9
